# Generated by Django 4.1.4 on 2022-12-23 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_type",
                    models.CharField(
                        choices=[
                            ("S", "SEEDS"),
                            ("G", "GRAINS"),
                            ("F", "FRUITS"),
                            ("B", "BERRIES"),
                        ],
                        default="S",
                        max_length=1,
                    ),
                ),
                (
                    "food_amounts",
                    models.CharField(
                        choices=[("S", "SMALL"), ("M", "MEDIUM"), ("L", "LARGE")],
                        default="S",
                        max_length=1,
                    ),
                ),
                (
                    "finch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main_app.finch"
                    ),
                ),
            ],
        ),
    ]
