# Generated by Django 4.1.4 on 2022-12-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_foodtype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foodtype",
            old_name="food_amounts",
            new_name="amounts",
        ),
        migrations.RenameField(
            model_name="foodtype",
            old_name="food_type",
            new_name="type",
        ),
    ]
