# Generated by Django 4.1.4 on 2022-12-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_rename_food_amounts_foodtype_amounts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodtype",
            name="amounts",
            field=models.CharField(
                choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                default="S",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="foodtype",
            name="type",
            field=models.CharField(
                choices=[
                    ("S", "Seeds"),
                    ("G", "Grains"),
                    ("F", "Fruits"),
                    ("B", "Berries"),
                ],
                default="S",
                max_length=1,
            ),
        ),
    ]
