# Generated by Django 4.1.4 on 2023-01-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_alter_foodtype_amounts_alter_foodtype_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Toy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("funness_scale", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="finch",
            name="toys",
            field=models.ManyToManyField(to="main_app.toy"),
        ),
    ]
